--!strict
-- Recipes (ModuleScript) — ReplicatedStorage.Config.Recipes
-- Every potion. A recipe can be brewed once all its ingredients are unlocked.
-- `Effect` is the name of a child module of ReplicatedStorage.Effects.

export type Recipe = {
	Id: string,
	DisplayName: string,
	Description: string, -- what it does to the customer (shown in the recipe book)
	Reaction: string, -- what the customer shouts after drinking it
	Ingredients: { [string]: number },
	SellPrice: number,
	BrewMultiplier: number, -- fancier potions take longer: brew time = base time * this
	Effect: string,
	Color: Color3,
	Order: number,
}

local Recipes: { [string]: Recipe } = {
	GiantHead = {
		Id = "GiantHead",
		DisplayName = "Giant Head Potion",
		Description = "Their head puffs up like a balloon!",
		Reaction = "My head!!",
		Ingredients = { Moonberry = 1, Glowshroom = 1 },
		SellPrice = 10,
		BrewMultiplier = 1,
		Effect = "BigHead",
		Color = Color3.fromRGB(255, 110, 200),
		Order = 1,
	},
	Rainbow = {
		Id = "Rainbow",
		DisplayName = "Rainbow Potion",
		Description = "They glow every color of the rainbow!",
		Reaction = "So sparkly!",
		Ingredients = { Moonberry = 2 },
		SellPrice = 12,
		BrewMultiplier = 1,
		Effect = "Rainbow",
		Color = Color3.fromRGB(255, 90, 90),
		Order = 2,
	},
	Tiny = {
		Id = "Tiny",
		DisplayName = "Tiny Potion",
		Description = "They shrink down to pocket size!",
		Reaction = "Eek, I'm tiny!",
		Ingredients = { Glowshroom = 2 },
		SellPrice = 12,
		BrewMultiplier = 1,
		Effect = "Tiny",
		Color = Color3.fromRGB(90, 190, 255),
		Order = 3,
	},
	Floaty = {
		Id = "Floaty",
		DisplayName = "Floaty Potion",
		Description = "They float up into the sky like a balloon!",
		Reaction = "Wheee!",
		Ingredients = { Starflower = 1, Glowshroom = 1 },
		SellPrice = 24,
		BrewMultiplier = 1.2,
		Effect = "Floaty",
		Color = Color3.fromRGB(255, 236, 130),
		Order = 4,
	},
	Twirly = {
		Id = "Twirly",
		DisplayName = "Twirly Potion",
		Description = "They spin like a spinning top!",
		Reaction = "So dizzy!!",
		Ingredients = { Starflower = 1, Moonberry = 1 },
		SellPrice = 24,
		BrewMultiplier = 1.2,
		Effect = "Twirl",
		Color = Color3.fromRGB(255, 150, 50),
		Order = 5,
	},
	Frosty = {
		Id = "Frosty",
		DisplayName = "Frosty Potion",
		Description = "They freeze into an ice statue. Brrr!",
		Reaction = "Brrrr!",
		Ingredients = { FrostCrystal = 1, Glowshroom = 1 },
		SellPrice = 45,
		BrewMultiplier = 1.5,
		Effect = "Frosty",
		Color = Color3.fromRGB(175, 240, 255),
		Order = 6,
	},
	Froggy = {
		Id = "Froggy",
		DisplayName = "Froggy Potion",
		Description = "They turn into a frog. Ribbit!",
		Reaction = "Ribbit!",
		Ingredients = { FrostCrystal = 1, Moonberry = 1, Starflower = 1 },
		SellPrice = 70,
		BrewMultiplier = 1.8,
		Effect = "Froggy",
		Color = Color3.fromRGB(110, 220, 90),
		Order = 7,
	},
	FireBreath = {
		Id = "FireBreath",
		DisplayName = "Fire Breath Potion",
		Description = "They breathe fire like a dragon!",
		Reaction = "HOT HOT HOT!",
		Ingredients = { EmberPepper = 1, Glowshroom = 1 },
		SellPrice = 90,
		BrewMultiplier = 1.6,
		Effect = "FireBreath",
		Color = Color3.fromRGB(255, 110, 40),
		Order = 8,
	},
	Dance = {
		Id = "Dance",
		DisplayName = "Dance Potion",
		Description = "A disco ball appears and they can't stop dancing!",
		Reaction = "Let's dance!",
		Ingredients = { EmberPepper = 1, Starflower = 1, Moonberry = 1 },
		SellPrice = 110,
		BrewMultiplier = 1.8,
		Effect = "Dance",
		Color = Color3.fromRGB(255, 80, 210),
		Order = 9,
	},
	Bubble = {
		Id = "Bubble",
		DisplayName = "Bubble Potion",
		Description = "They float away inside a giant bubble. Pop!",
		Reaction = "I'm in a bubble!",
		Ingredients = { CloudPuff = 1, Moonberry = 1 },
		SellPrice = 120,
		BrewMultiplier = 1.8,
		Effect = "Bubble",
		Color = Color3.fromRGB(140, 225, 255),
		Order = 10,
	},
	Ghost = {
		Id = "Ghost",
		DisplayName = "Ghost Potion",
		Description = "They turn into a see-through ghost. Boo!",
		Reaction = "Boooo!",
		Ingredients = { CloudPuff = 1, FrostCrystal = 1 },
		SellPrice = 150,
		BrewMultiplier = 2,
		Effect = "Ghost",
		Color = Color3.fromRGB(205, 215, 255),
		Order = 11,
	},
	Rocket = {
		Id = "Rocket",
		DisplayName = "Rocket Potion",
		Description = "They blast off into the sky and float back down!",
		Reaction = "To the moon!",
		Ingredients = { EmberPepper = 1, CloudPuff = 1, Starflower = 1 },
		SellPrice = 220,
		BrewMultiplier = 2.4,
		Effect = "Rocket",
		Color = Color3.fromRGB(255, 175, 60),
		Order = 12,
	},
}

return Recipes
